#define AUTOCONF_INCLUDED
#ifndef AUTOCONF_Configuration_H
#define AUTOCONF_Configuration_H
#include <kernel/gen_config.h>
#include <elfloader/gen_config.h>
#include <sel4/gen_config.h>
#include <usbdrivers/gen_config.h>
#include <sel4vka/gen_config.h>
#include <sel4utils/gen_config.h>
#include <sel4platsupport/gen_config.h>
#include <sel4serialserver/gen_config.h>
#include <sel4debug/gen_config.h>
#include <sel4test/gen_config.h>
#include <sel4muslcsys/gen_config.h>
#include <sel4vmm/gen_config.h>
#include <camkes_config/gen_config.h>
#include <capdl_loader_app/gen_config.h>
#include <utils/gen_config.h>
#include <platsupport/gen_config.h>
#include <ethdrivers/gen_config.h>
#endif